---
title: "Text processing for lyrics analysis"
output:
  html_document:
    df_print: paged
  html_notebook:
    theme: flatly
---


## Step 1 - Load libraries and read data

```{r, echo=TRUE, message=FALSE, warning=FALSE}
### load library
library(tidyr)
library(dplyr)  ## data manipulation
library(tm)  ## data cleaning
library(tidytext) 
library(stringr) 
library(DT) ## show data in table format
```

```{r echo=TRUE}
### load data
data = read.csv("lyrics.csv", stringsAsFactors = FALSE)
datatable(data)
```


## Step 2 - Data processing

In this part, **tm** package is used to process the text data such as removing stopwords, conducting words stemming and completion, and creating tidy format for further analysis.s

```{r}
# define the function of removing "-"
removedash = function(x) {
  str_replace_all(x, pattern = "-", replacement = " ")
}

# filter the metal and rock music
data1 = data %>%
  mutate_all(., removedash) %>%
  filter(genre %in% c("Metal", "Rock", "Pop"))

# define function of removing the white space of lyrics
leadingwhitespace = content_transformer(function(x) str_trim(x, side = "both"))

# remove stop words
data("stop_words")
word <- c("lot", "today", "months", "month", "wanna", "wouldnt", "wasnt", "ha", "na", "ooh", "da",
          "gonna", "im", "dont", "aint", "wont", "yeah", "la", "oi", "nigga", "fuck",
          "hey", "year", "years", "last", "past", "feel")
stop_words = c(stop_words$word, word)

# use tm package to clean the lyrics
corpus = VCorpus(VectorSource(data1$lyrics)) %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removePunctuation) %>%
  tm_map(removeWords, character(0)) %>%
  tm_map(removeWords, stop_words) %>%
  tm_map(removeNumbers) %>%
  tm_map(stripWhitespace) %>%
  tm_map(leadingwhitespace)

# words stemming and stem completion

# stem words and converts tm object to tidy object
stemmed = tm_map(corpus, stemDocument) %>%
  tidy() %>%
  select(text)

# create tidy format of dictionary to be used for completing stems
dict = tidy(corpus) %>%
  select(text) %>%
  unnest_tokens(dictionary, text)

# combine stems and dictionary into the same tibble
completed = stemmed %>%
  mutate(id = row_number()) %>%
  unnest_tokens(stems, text) %>%
  bind_cols(dict)

# stem completion -- complete the stems by picking the corresponding word with the highest frequency
completed = completed %>%
  group_by(stems) %>%
  count(dictionary) %>%
  mutate(word = dictionary[which.max(n)]) %>%
  ungroup() %>%
  select(stems, word) %>%
  distinct() %>%
  right_join(completed) %>%
  select(-stems)

# utilize the processed words to resemble the structure of the original lyrics
completed = completed %>%
  group_by(id) %>%
  summarize(stemmedwords = str_c(word, collapse = " ")) %>% # to create a stemmed lyrics 
  ungroup()

# keep the track of the processed lyrics with their own ID
data1 = data1 %>%
  mutate(id = row_number()) %>%
  inner_join(completed)


# clean the song's name column
corpus_song = VCorpus(VectorSource(data1$song)) %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removePunctuation) %>%
  tm_map(removeWords, character(0)) %>%
  tm_map(removeWords, stop_words) %>%
  tm_map(removeNumbers) %>%
  tm_map(stripWhitespace) %>%
  tm_map(leadingwhitespace)

processed_song = corpus_song %>%
  tidy() %>%
  mutate(id = row_number()) %>%
  select(id, text)

data2 = data1 %>%
  inner_join(processed_song)
```


## Step 3 - Split the data

```{r}
# rename specific columns' names
colnames(data2)[7] = "clean_lyrics"
colnames(data2)[8] = "clean_song"

# separate the metal and pop data
metal = data2 %>%
  filter(genre == "Metal")

pop = data2 %>%
  filter(genre == "Pop")

datatable(metal)
datatable(pop)
```


## Step 4 - Save data

```{r}
save(metal, file = "metal.RData")
save(pop, file = "pop.RData")
```


